version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  discovery-service:
    image: discovery-service
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  config-server:
    image: config-server
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - microservices-network

  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - config-server
    networks:
      - microservices-network

  user-service:
    image: user-service
    build:
      context: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - config-server
      - kafka
    networks:
      - microservices-network

  notification-service:
    image: notification-service
    build:
      context: ./notification-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
      - config-server
      - kafka
      - mailhog
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge